### ISSUE TITLE
thanks ! it worked!

### ISSUE THREAD

**Issue by kindmartin** [bdutro/ibm_pw_clear#1]
Hi bdutro ! you save me a multi thousand usd box i needed to admin pass reset today for a project. 
here my contribution info links:

1- tested in a x3650 M4 HD, worked !
2.- I didnt know any on UEFI and PXE, but this next links helpme a lot. At the end I didnt use PXE but a USB pendrive with your file at /efi/boot/BOOTX64.efi
good on PXE ->
https://www.youtube.com/watch?v=5qyTLfJrQM4

a multi function tftp DHCP server
https://www.vercot.com/~serva/download.html

**Comment by bdutro** [comment]
Glad it worked for you! I'll add a note that it works for the M4 models.
