### ISSUE TITLE
How to make a bootable cd ?

### ISSUE THREAD

**Issue by LIONNNNNN** [bdutro/ibm_pw_clear#2]
Hello,

i tried it with a cd but it couldn’t boot...is there anything that I have to do before ? Or do I need a os running on the cd for the .efi?

greetings from Germany

**Comment by bdutro** [comment]
How did you create the CD?

**Comment by LIONNNNNN** [comment]
> How did you create the CD?

With CDBurnerXP finalized, do I have to use a special direction ?

**Comment by LIONNNNNN** [comment]
It know looks like efi/boot/BOOTX64.efi

BTW. I used you premade file

**Comment by bdutro** [comment]
I think you need to place bootx64.efi at the root of the CD. Alternatively, you can try making a CD with the Tianocore EFI shell. You'll be able to tell if it's working based on whether the shell comes up, and you can run the password clear tool from inside the shell.

**Comment by LIONNNNNN** [comment]
> I think you need to place bootx64.efi at the root of the CD. Alternatively, you can try making a CD with the Tianocore EFI shell. You'll be able to tell if it's working based on whether the shell comes up, and you can run the password clear tool from inside the shell.

The Problem is wether I put it directly into the root, or in the destination above, when I want to boot from CD in the bios it doesn’t work and I’m back at the start point of the bios

**Comment by bdutro** [comment]
That sounds like the expected behavior. If you boot directly into the password reset tool it will immediately reboot. Is the password not getting reset?

**Comment by LIONNNNNN** [comment]
No the server also don’t restart...and the password isn’t reseted...the server don’t find a bootable file on the cd but there is your efi, one time at the root and on the other cd at the destination above

**Comment by bdutro** [comment]
I see. One other thing you can try is the rEFInd bootable CD image (http://www.rodsbooks.com/refind/getting.html). You can then put the password tool on a USB drive and access it from the EFI shell on the CD image.

**Comment by LIONNNNNN** [comment]
Even usb boot is disabled, you think with the shell I can access it? How do I start the .efi ?

**Comment by bdutro** [comment]
Once you get into an EFI shell, you can mount a USB drive and run the tool from it. The rEFInd CD includes an EFI shell.

**Comment by LIONNNNNN** [comment]
It worked with your last idea...thank you soooo much I tried it for 1 year :)
